### ISSUE TITLE
Store live blog posts in wp_posts, not wp_comments

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/liveblog#377] opened 2018-03-21 18:39 UTC
Store live blog posts in `wp_posts`, not `wp_comments`. Updates should be children of the main post `wp_post`.

This will allow you to attach authors in a standard way, instead of via `commentmeta`.

**Comment by philipjohn** [comment] 2018-05-10 17:09
Closing as duplicate of #282

**Closed by philipjohn** 2018-05-10 17:09 UTC
