### ISSUE TITLE
Feature Request: Backend UI for managing liveblog posts

### ISSUE THREAD

**Issue by mikeselander** [Automattic/liveblog#267] opened 2016-09-14 15:11 UTC
We've found several situations where it would be particularly useful to edit the liveblog "posts" in bulk and see information about their status in the edit post screen. The ability to either bulk delete or simply see the number of liveblog posts on without having to paginate through them on the front end would save significant amounts of time for both editorial and development. 

I envision a list table of posts and actions underneath the status trigger on post edit screen. Columns for action (checkbox), content, date/time posted, and author would cover most needs. I imagine for most needs live-reload on the table wouldn't be strictly necessary - but potentially helpful. The important thing is to see and be able to edit all current live-posts in their entirety.

This feature would have helped us track down several issues in development faster and fix any human-error issues that were flagged. Our client has echoed this desire and would love to see this enhancement.

Please let me know if you have any more questions/thoughts on this enhancement!

**Comment by philipjohn** [comment] 2016-09-15 12:19
Agreed! Closing as a dupe of #216 but will copy your comments across as they're very useful.

**Closed by philipjohn** 2016-09-15 12:19 UTC
