### ISSUE TITLE
Issue with update live blog Entry

### ISSUE THREAD

**Issue by achaitanyajami** [Automattic/liveblog#371] opened 2018-03-13 14:37 UTC
Hi Automattic,

I have observed a strange behavior in the Liveblog plugin when an update I made to live blog entry.
Here is the screenshot.
<img width="848" alt="screen shot 2018-03-13 at 7 09 29 pm" src="https://user-images.githubusercontent.com/27680483/37345097-219132fe-26f2-11e8-8ec7-3cd4c14fa6fd.png">

I can see this issue with the latest version as well.

Here is the how I can reproduce the issue:
* Create An Live blog entry.
* Edit the same LiveBlog entry and add extra content to it and update the content.
* Now delete the same entry which you have updated.
* Now you will see content is deleted without any alert information where we usually get when deleting the content.
* Now reload the page. You will see the above screen.

So, I have gone through the code and found that we are not checking if an entry exists in the DB.
In `liveblog/classes/class-wpcom-liveblog-entry.php`  function `get_fields_for_render` Line 97
`$entry_id     = $this->replaces ? $this->replaces : $this->comment->comment_ID;` not checking if this`$entry_id`  ID exists or not.

So I simply added this 2 lines of code in `liveblog/classes/class-wpcom-liveblog-entry.php`  function `render` after Line 130
`if ( ! wp_get_comment_status( $entry['entry_id'] ) ) {
			return $output;
		}`

So that I can only display/loop the file only if an entry ID exists.

Hope this will be Helpful, Sorry that I don't have permission to create a PR for this fix.

**Comment by rebeccahum** [comment] 2018-03-13 14:59
@achaitanyajami Thanks for reporting this issue!  

> Hope this will be Helpful, Sorry that I don't have permission to create a PR for this fix.

You should definitely be able to make a PR.  Do you want to try to give that a shot?

**Comment by achaitanyajami** [comment] 2018-03-13 20:32
Yes, @rebeccahum

**Comment by rebeccahum** [comment] 2018-03-13 21:32
Awesome! Looking forward to seeing your PR @achaitanyajami.

**Comment by achaitanyajami** [comment] 2018-03-26 06:21
Small change in the code,
 since `wp_get_comment_status ` only checks for 
`if ( $approved == null )
		return false;
	elseif ( $approved == '1' )
		return 'approved';
	elseif ( $approved == '0' )
		return 'unapproved';
	elseif ( $approved == 'spam' )
		return 'spam';
	elseif ( $approved == 'trash' )
		return 'trash';
	else
		return false;`

I have changed the code to `$comment = get_comment( $entry['entry_id'] );
		if ( $comment && 'liveblog' !== $comment->comment_approved ) {
			return $output;
		}`
since `wp_get_comment_status ` wont check for flag called `liveblog`

**Comment by rebeccahum** [comment] 2018-04-10 14:36
@achaitanyajami Can you confirm which Liveblog version you are using?

**Comment by rebeccahum** [comment] 2018-04-10 15:01
Using 1.7.1, the latest version, I am unable to reproduce.

**Comment by achaitanyajami** [comment] 2018-04-13 07:17
Hi @rebeccahum,
I am using the same version `1.7.1` on a clean install and still facing the issue.

Deep diving into this LIVEBLOG code, I found that code in the below PR is main cause to break the live blog.
https://github.com/Automattic/liveblog/pull/385

**Comment by rebeccahum** [comment] 2018-04-13 17:42
@achaitanyajami Do you have an updated screenshot for what you see or updated steps for 1.7.1? The "Load more entries" button was replaced with pagination tab buttons in 1.7.1.

**Comment by GaryJones** [comment] 2024-06-07 11:36
Closing for lack of updates.

**Closed by GaryJones** 2024-06-07 11:36 UTC
Labels: Status: reporter feedback
