### ISSUE TITLE
Wrong parameter passed to get_liveblog_metadata()

### ISSUE THREAD

**Issue by dhanendrannewscorp** [Automattic/liveblog#589] opened 2018-11-01 13:43 UTC
**Issue 1:**
In [`print_liveblog_metadata()`](https://github.com/Automattic/liveblog/blob/master/liveblog.php#L1859) function, there is a small mistake in the [`get_liveblog_metadata()`](https://github.com/Automattic/liveblog/blob/master/liveblog.php#L1866) function call.

Instead of passing [`WP_Post`](https://github.com/Automattic/liveblog/blob/master/liveblog.php#L1797) object, post id been passed in.

**Issue 2:**
In the [DocBlock](https://github.com/Automattic/liveblog/blob/master/liveblog.php#L868) of `entries_for_json()`, param type should be mentioned.

**Comment by nickdaugherty** [comment] 2018-11-01 17:15
Thanks for the report - this appears to be a duplicate of https://github.com/Automattic/liveblog/issues/557 so I'll close this in favor of that one.

**Closed by nickdaugherty** 2018-11-01 17:15 UTC
