### ISSUE TITLE
HTML tables double-encoded

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/liveblog#380] opened 2018-03-21 22:21 UTC
HTML tables are double-encoded in HTML blocks.

### Steps to reproduce
Under Add New Entry
* Set an author
* Click the `<>` button
* Paste in this HTML
```html
<section class="viz">
    <header class="viz">
        <p class="subtitle">Share of Americans, under 65, who are uninsured*</p>
    </header>
    <table class="viz full" data-carpenter-slug="barry-jester.obamacarelayland.4">
        <thead>
            <tr>
                <th colspan="1" class="text">Year</th>
                <th colspan="1" class="number"></th>
                <th colspan="1" class="bars" style="width:30%">States where Medicaid expanded</th>
                <th colspan="1" class="number"></th>
                <th colspan="1" class="bars" style="width:30%">non-expansion states</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text">2013</td>
                <td class="number" data-suffix="%" data-suffixpadding="1.1em">14.9%</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:65.63876651982379%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
                <td class="number" data-suffix="%" data-suffixpadding="1.1em">18.4%</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:81.05726872246696%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
            </tr>
            <tr>
                <td class="text">2014</td>
                <td class="number" style="padding-right: 1.1em;">10.9</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:48.01762114537445%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
                <td class="number" style="padding-right: 1.1em;">16.0</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:70.48458149779736%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
            </tr>
            <tr>
                <td class="text">2015</td>
                <td class="number" style="padding-right: 1.1em;">8.2</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:36.12334801762114%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
                <td class="number" style="padding-right: 1.1em;">14.0</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:61.67400881057269%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
            </tr>
            <tr>
                <td class="text">2016</td>
                <td class="number" style="padding-right: 1.1em;">7.8</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:34.36123348017621%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
                <td class="number" style="padding-right: 1.1em;">14.7</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:64.75770925110133%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
            </tr>
            <tr>
                <td class="text">2017 (Jan-Sep)</td>
                <td class="number" style="padding-right: 1.1em;">7.5</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:33.03964757709251%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
                <td class="number" style="padding-right: 1.1em;">15.7</td>
                <td class="bars" style="width:30%">
                    <div class="bar" style="width:69.16299559471365%; position: relative; background-color:#ED713A; left: 0%">-</div>
                </td>
            </tr>
        </tbody>
    </table>
    <footer class="viz">
        <p class="notes">* At time of survey. Number of states with Medicaid expansion changed over time.</p>
        <p class="source">Sources: NCHS, National Health Interview Survey </p>
    </footer>
</section>
```
* Click Save
* Click Publish New Entry

### Expected
![screenshot 2018-03-21 18 20 39](https://user-images.githubusercontent.com/86784/37740575-9b68e778-2d34-11e8-8ff8-dbeb578fab24.png)

### Actual
![screenshot 2018-03-21 18 18 16](https://user-images.githubusercontent.com/86784/37740467-3d8b909c-2d34-11e8-8e8c-ab03167fd617.png)

### Generated HTML
```html
<div class="liveblog-entry-content"><p></p>
<div>
<div id="liveblog-codeblock-identifier-HTML">
<section class="viz">
<header class="viz">
<p class="subtitle">Share of Americans, under 65, who are uninsured*</p>
</header>
<table class="viz full" data-carpenter-slug="barry-jester.obamacarelayland.4">
<thead>
<tr>
<th colspan="1" class="text">Year</th>
<th colspan="1" class="number"></th>
<th colspan="1" class="bars" style="width:30%">States where Medicaid expanded</th>
<th colspan="1" class="number"></th>
<th colspan="1" class="bars" style="width:30%">non-expansion states</th>
</tr>
</thead>
<tbody>
<tr>
<td class="text">2013</td>
<td class="number" data-suffix="%" data-suffixpadding="1.1em">14.9%</td>
<td class="bars" style="width:30%">
                    &lt;div class="bar" style="width:65.63876651982379%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-</td>
</tr>
</tbody>
</table>
</section>
</div>
18.4%

                    &lt;div class="bar" style="width:81.05726872246696%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
</div>

2014
10.9

                    &lt;div class="bar" style="width:48.01762114537445%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                
16.0

                    &lt;div class="bar" style="width:70.48458149779736%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                


2015
8.2

                    &lt;div class="bar" style="width:36.12334801762114%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                
14.0

                    &lt;div class="bar" style="width:61.67400881057269%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                


2016
7.8

                    &lt;div class="bar" style="width:34.36123348017621%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                
14.7

                    &lt;div class="bar" style="width:64.75770925110133%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                


2017 (Jan-Sep)
7.5

                    &lt;div class="bar" style="width:33.03964757709251%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                
15.7

                    &lt;div class="bar" style="width:69.16299559471365%; position: relative; background-color:<span class="liveblog-hash term-ed713a">ed713a</span>; left: 0%”&gt;-
                

<footer class="viz">
<p class="notes">* At time of survey. Number of states with Medicaid expansion changed over time.</p>
<p class="source">Sources: NCHS, National Health Interview Survey </p>
</footer>
</div>
```

**Comment by liam-defty** [comment] 2018-03-23 16:11
After a little investigation it appears this is because of the hashtag feature. The regex that pulls out hashtags from an entry will need editing, perhaps a solution could be to ignore any hashtags that are in an inline style attribute.

**Comment by paulschreiber** [comment] 2018-05-01 16:43
To work around this, I had to do two things: https://github.com/Automattic/liveblog/commit/712b2119c76007debd92e8725662880b0ac9eaf7
• disable the hashtag filter
• no longer call `wp_filter_post_kses()` when inserting comments

I tried to disable the hashtag feature with a filter:
```php
add_filter( 'liveblog_features', function( $features ) {
  if ( ( $key = array_search( 'hashtags', $features, true ) ) !== false ) {
    unset( $features[ $key ] );
    }
  return $features;
});
```
…but it never ran.

**Comment by combs** [comment] 2018-05-11 19:03
We couldn't get the liveblog_features filter to do anything either. Is it the same problem as this?
https://github.com/Automattic/liveblog/pull/384

and the CSS colors turning into hashtags sounds related to #418?

**Comment by philipjohn** [comment] 2018-10-08 08:47
Yep, sounds like this is the same root cause as #418 so let's close this in favour of that issue and track there.

**Closed by philipjohn** 2018-10-08 08:47 UTC
